app/analysis/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField, SelectField, SelectMultipleField, FloatField, IntegerField, FileField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_wtf.file import FileField, FileAllowed, FileRequired


class UploadForm(FlaskForm):
    file = FileField('File')
    submit = SubmitField('Submit')

app/analysis/__init__.py
from flask import Blueprint

bp = Blueprint('analysis', __name__)

from app.analysis import routes

app/analysis/routes.py
from flask import render_template, redirect, url_for, flash, request, \
                    current_app, make_response, jsonify, abort, send_from_directory
from flask_login import login_required, current_user, logout_user
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from app import db
from app.analysis import bp
import datetime
import os
from app.decorators import server_valid_authentication_required, project_required, send_variants, \
    project_data_required, update_known_variants, update_known_variants_redis_DB
from app.analysis.forms import UploadForm

@bp.route('/index')
def index():
    flash('INDEX','success')
    return( render_template( 'analysis/index.html' ))

@bp.errorhandler(413)
def too_large(e):
    return "File is too large", 413

@bp.route('/uploaded', methods=["GET", "POST"])
@login_required
@project_required
@server_valid_authentication_required
def uploaded():
    USER_UPLOAD_FOLDER = os.path.join( current_app.config['UPLOAD_FOLDER'], 'VCF-ANALYSIS', current_user.server_username )
    files = os.listdir( USER_UPLOAD_FOLDER )
    NOW = datetime.datetime.now()
    FILE_CHARS_DICT = dict()
    for item in os.scandir( USER_UPLOAD_FOLDER ):
        ### get name
        if item.name not in FILE_CHARS_DICT:
            FILE_CHARS_DICT.update({ item.name : dict() })
        ### get size
        SIZE_KB = str(round(item.stat().st_size / (1024), 3))
        SIZE_MB = str(round(item.stat().st_size / (1024 * 1024), 3))
        SIZE_GB = str(round(item.stat().st_size / (1024 * 1024 * 1024), 3))
        if SIZE_GB[0] == "0":
            if SIZE_MB[0] == "0":
                SIZE_APPEND = SIZE_KB
                SIZE_FORMAT = 'KB'
            else:
                SIZE_APPEND = SIZE_MB
                SIZE_FORMAT = 'MB'
        else:
            SIZE_APPEND = SIZE_GB
            SIZE_FORMAT = 'GB'
        FILE_CHARS_DICT[ item.name ].update({ 'size_value': SIZE_APPEND, 'size_format': SIZE_FORMAT })
        EXP = datetime.datetime.fromtimestamp( item.stat().st_ctime ) + datetime.timedelta(days=1)
        DIFF = EXP - NOW
        FILE_CHARS_DICT[ item.name ].update({ 'expiration': str(DIFF).split('.', 2)[0] })
    return render_template('analysis/upload.html', FILE_CHARS_DICT = FILE_CHARS_DICT )


@bp.route('/', methods=["GET", "POST"])
@login_required
@project_required
@server_valid_authentication_required
def upload():
    USER_UPLOAD_FOLDER = os.path.join( current_app.config['UPLOAD_FOLDER'], 'VCF-ANALYSIS', current_user.server_username )
    uploaded_file = request.files["file"]
    filename = secure_filename(uploaded_file.filename)
    if filename != '':
        file_ext = os.path.splitext(filename)[1]
        if file_ext not in current_app.config['ALLOWED_EXTENSIONS']:
            return "Invalid File Type", 400
        uploaded_file.save(os.path.join(USER_UPLOAD_FOLDER, filename))
    #return '', 204
    return( redirect(url_for('analysis.uploaded')) )



@bp.route('/uploads/<filename>')
def uploads(filename):
    USER_UPLOAD_FOLDER = os.path.join( current_app.config['UPLOAD_FOLDER'], 'VCF-ANALYSIS', current_user.server_username )
    return send_from_directory( USER_UPLOAD_FOLDER, filename )

app/templates/analysis/blank.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}




{% endblock %}

app/templates/analysis/index.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}



{% endblock %}

app/templates/analysis/upload.html
{% extends "base_DXcator.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<html>
  <head>
    <title>File Upload</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
  </head>
  <body>
    <h1>VCF File Upload</h1>
    <form action="{{ url_for('analysis.upload') }}" class="dropzone">
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.js"></script>

    <hr>
    <div style="text-align: center;">
      <button class="btn btn-success" onClick="window.location.reload();">Show Below</button>
    </div>

    <hr>
    <div style='font-size: 100%; margin-top: 3%; max-width: 100%;'>
    <table class="table table-hover" >
      <thead class="thead-dark">
        <tr style="background-color: black; color: white;" >
          <th class="ui-helper-center">
              Index
          </th>
          <th class="ui-helper-center">
              File
          </th>
          <th class="ui-helper-center">
              Size
          </th>
          <th class="ui-helper-center">
              Expires in
          </th>
          <th class="ui-helper-center" style="width: 8%;">
              Analyze
          </th>
          <th class="ui-helper-center" style="width: 5%;">
              Download
          </th>
        </tr>
      </thead>
      <tbody>
        {% for file, file_dict in FILE_CHARS_DICT.items() %}
        <tr>
          <td class="ui-helper-center">
              {{ loop.index }}
          </td>
          <td class="ui-helper-center">
              {{ file }}
          </td>
          <td class="ui-helper-center">
              {{ file_dict['size_value'] }} ({{ file_dict['size_format']}})
          </td>
          <td class="ui-helper-center">
            {{ file_dict['expiration'] }} (h)
          </td>
          <td class="ui-helper-center">
            <a href="{{ url_for('analysis.uploads', filename = file )}}">
              <button class="btn btn-success" id="{{ file }}_BUTTON_ANALYSIS" style="width: 100%; white-space: normal;">
                go
              </button>
            </a>
          </td>
          <td class="ui-helper-center">
            <a href="{{ url_for('analysis.uploads', filename = file )}}">
              <button class="btn btn-info" id="{{ file }}_BUTTON_DOWNLOAD" style="border: 1px solid #308eff; width: 100%; white-space: normal;">
                get
              </button>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>

  </body>
</html>



{% endblock %}